version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - run:
          name: Install cookiecutter
          command: |
            python3 -m venv venv
            . venv/bin/activate

            pip install cookiecutter

      - run:
          name: Bootstrap the project
          command: |
            . venv/bin/activate
            make

      - setup_remote_docker
      - run:
          name: Build test docker image
          command: |
            cd testing/django
            docker build -t f213/django .

workflows:
  version: 2
  ci:
    jobs:
      - build
