version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          name: Install cookiecutter
          command: |
            python3 -m venv venv
            . venv/bin/activate

            pip install cookiecutter

      - run:
          name: Bootstrap the project
          command: ./test.sh

workflows:
  version: 2
  ci:
    jobs:
      - build
